import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function formatProcessingTime(ms: number): string {
  if (ms < 1000) return `${Math.round(ms)}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}

export function countWords(text: string): number {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportAsJSON(data: object, filename: string = "soap-note.json"): void {
  downloadBlob(
    new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }),
    filename
  );
}

export function exportAsText(soapNote: {
  subjective: string;
  objective: string;
  assessment: string;
  plan: string;
}, filename: string = "soap-note.txt"): void {
  const text = [
    "SOAP NOTE",
    "=========",
    "",
    "SUBJECTIVE (S):",
    soapNote.subjective,
    "",
    "OBJECTIVE (O):",
    soapNote.objective,
    "",
    "ASSESSMENT (A):",
    soapNote.assessment,
    "",
    "PLAN (P):",
    soapNote.plan,
    "",
    `Generated by SOAPFlow — ${new Date().toLocaleString()}`,
  ].join("\n");

  downloadBlob(new Blob([text], { type: "text/plain" }), filename);
}

export function toPrintableHtml(text: string): string {
  return text
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;")
    .replace(/\n/g, "<br>");
}

export function printSOAPNote(soapNote: {
  subjective: string;
  objective: string;
  assessment: string;
  plan: string;
}, metadata?: { model?: string; mode?: string; processing_time_ms?: number }): void {
  const timestamp = new Date().toLocaleString();
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>SOAP Note — SOAPFlow</title>
      <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: 'Georgia', serif; font-size: 13px; line-height: 1.7; color: #1a1a1a; padding: 32px; max-width: 800px; margin: 0 auto; }
        .header { border-bottom: 2px solid #0ea5e9; padding-bottom: 12px; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: baseline; }
        .title { font-size: 20px; font-weight: 700; color: #0c4a6e; letter-spacing: -0.3px; }
        .subtitle { font-size: 11px; color: #64748b; }
        .section { margin-bottom: 18px; page-break-inside: avoid; }
        .section-label { font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #0ea5e9; margin-bottom: 4px; }
        .section-title { font-size: 14px; font-weight: 700; color: #0c4a6e; margin-bottom: 6px; border-left: 3px solid #0ea5e9; padding-left: 8px; }
        .section-content { font-size: 13px; color: #1e293b; line-height: 1.8; padding-left: 11px; }
        .footer { margin-top: 28px; padding-top: 12px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #94a3b8; display: flex; justify-content: space-between; }
        .meta-badge { display: inline-block; background: #f0f9ff; color: #0369a1; border: 1px solid #bae6fd; border-radius: 4px; padding: 2px 8px; font-size: 10px; font-weight: 600; margin-right: 4px; }
        @media print { body { padding: 16px; } @page { margin: 2cm; } }
      </style>
    </head>
    <body>
      <div class="header">
        <div>
          <div class="title">SOAP Note</div>
          <div class="subtitle">Generated by SOAPFlow · ${timestamp}</div>
        </div>
        <div>
          ${metadata?.mode ? `<span class="meta-badge">${metadata.mode}</span>` : ""}
          ${metadata?.model ? `<span class="meta-badge">${metadata.model}</span>` : ""}
        </div>
      </div>
      <div class="section">
        <div class="section-label">S</div>
        <div class="section-title">Subjective</div>
        <div class="section-content">${toPrintableHtml(soapNote.subjective)}</div>
      </div>
      <div class="section">
        <div class="section-label">O</div>
        <div class="section-title">Objective</div>
        <div class="section-content">${toPrintableHtml(soapNote.objective)}</div>
      </div>
      <div class="section">
        <div class="section-label">A</div>
        <div class="section-title">Assessment</div>
        <div class="section-content">${toPrintableHtml(soapNote.assessment)}</div>
      </div>
      <div class="section">
        <div class="section-label">P</div>
        <div class="section-title">Plan</div>
        <div class="section-content">${toPrintableHtml(soapNote.plan)}</div>
      </div>
      <div class="footer">
        <span>SOAPFlow — AI Clinical Documentation Assistant</span>
        <span>Printed: ${timestamp}</span>
      </div>
    </body>
    </html>
  `;

  const win = window.open("", "_blank", "width=850,height=700");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => {
    win.print();
    win.close();
  }, 300);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    const el = document.createElement("textarea");
    el.value = text;
    el.setAttribute("readonly", "");
    el.style.position = "absolute";
    el.style.left = "-9999px";
    document.body.appendChild(el);
    el.select();
    const success = document.execCommand("copy");
    document.body.removeChild(el);
    return success;
  }
}
